name: New
favicon: null
layout_spectrum: 0.33772606449201703
typography_spectrum: 0.36826709215529263
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.22902541933581233
  lightness: 0.9698842903599143
  saturation: 0.665563213871792
  rhythmicContrast: 0.009221418295055628
purpose: []
