name: New
favicon: null
layout_spectrum: 1
typography_spectrum: 0.43956
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#280000'
    - '#191919'
    - '#e9e9e9'
    - '#ff4040'
    - '#5d1010'
  brandStrength: 1
  lightness: 0.625
  saturation: 0.75
  rhythmicContrast: 0.75
purpose: []
